// ================================================================
//  常量定义 — 翻译字典、演示数据、AI 回复、样式色板
// ================================================================

import type { Project, Translations } from "./types";

// ── 双语翻译字典 ──────────────────────────────────────────────
export const T: Record<"zh" | "en", Translations> = {
  zh: {
    brand: "BrightSun BIM 合规",
    tagSub: "ISO 19650 信息合规体检平台",
    hero1: "CDE 提交前的",
    hero2: "最后一道闸",
    heroSub: "上传 IFC / RVT / DWG 模型，5 分钟获得命名合规检查报告与修复指南。无需配置规则，拖拽即用。",
    cta: "开始检查",
    ctaDemo: "查看示例报告",
    feat1t: "命名合规检查", feat1d: "UK NA 七段式命名（Project-Originator-Volume-Level-Type-Role-Number）、状态码（S0–S7）、版本号自动校验",
    feat2t: "Uniclass 2015 分类", feat2d: "自动检查每个构件的分类码是否存在且符合 Uniclass 2015 标准",
    feat3t: "EIR 属性完整性", feat3d: "预置典型 EIR 必填属性模板，一键检查防火等级、荷载等关键参数",
    feat4t: "人话修复指南", feat4d: "AI 自动生成面向 Revit 建模员的操作步骤，初级人员也能看懂直接改",
    statModels: "构件已分析", statUsers: "工程师在用", statTime: "平均审计时间",
    login: "登录", signup: "注册", email: "邮箱", password: "密码",
    loginWith: "或使用以下方式登录",
    nav_dash: "工作台", nav_viewer: "模型查看", nav_pricing: "升级 Pro", nav_settings: "设置",
    dash_welcome: "欢迎回来",
    dash_quick: "快速操作",
    dash_upload: "上传新模型", dash_audit: "AI 审计列表", dash_export: "导出报告",
    dash_active: "进行中的项目",
    dash_stats: "本月统计",
    upload_title: "上传模型文件",
    upload_hint: "拖拽文件到此处，或点击选择",
    upload_formats: "支持格式：IFC · FBX · OBJ · GLB · GLTF",
    upload_note_full: "IFC 格式：支持 3D 查看 + AI 数据分析",
    upload_note_view: "FBX / OBJ / GLB 格式：仅支持 3D 查看",
    viewer_ai: "合规检查报告",
    viewer_ai_ready: "模型已加载，正在运行合规检查...",
    viewer_placeholder: "有问题？输入关键词搜索相关合规条目",
    viewer_fbx_note: "当前为 FBX 格式，仅支持 3D 查看，不支持 AI 分析",
    pricing_title: "选择适合你的方案",
    pricing_sub: "从免费开始，随时升级",
    free: "免费版", pro: "专业版", enterprise: "企业版",
    free_price: "$0", pro_price: "$99/月", ent_price: "联系我们",
    per_month: "/月",
    current_plan: "当前方案",
    upgrade: "立即升级",
    contact_sales: "联系销售",
    f1: "3 个项目", f2: "50MB 单文件", f3: "基础 AI 审计", f4: "社区支持",
    p1: "无限项目", p2: "500MB 单文件", p3: "深度 AI 审计", p4: "导出 Excel/PDF", p5: "优先支持", p6: "团队协作",
    e1: "私有化部署", e2: "无限文件大小", e3: "定制 AI 模型", e4: "API 接口", e5: "专属客户经理", e6: "SLA 保障",
    logout: "退出登录",
    models_count: "个构件",
    status_parsing: "解析中",
    status_auditing: "审计中",
    status_done: "已完成",
    status_view_only: "仅查看",
    lang: "EN",
    col_project: "项目名称", col_format: "格式", col_elements: "构件数", col_status: "状态", col_date: "日期",
    stat_total_projects: "总项目", stat_elements: "构件总数", stat_audits_done: "审计完成", stat_completeness: "参数完整率",
    q1: "查看所有命名错误", q2: "查看缺失 Uniclass 分类的构件", q3: "生成 EIR 合规报告",
    view: "查看",
    recommended: "推荐",
  },
  en: {
    brand: "BrightSun BIM Compliance",
    tagSub: "ISO 19650 Information Compliance Platform",
    hero1: "The last gate before",
    hero2: "CDE submission",
    heroSub: "Upload IFC / RVT / DWG models, get a naming compliance report with fix-it guide in 5 minutes. Zero configuration, just drag and drop.",
    cta: "Start Checking",
    ctaDemo: "View Sample Report",
    feat1t: "Naming Compliance", feat1d: "UK NA 7-field naming (Project-Originator-Volume-Level-Type-Role-Number), status codes (S0–S7), revision validation",
    feat2t: "Uniclass 2015", feat2d: "Auto-check every element's classification code against the Uniclass 2015 standard",
    feat3t: "EIR Completeness", feat3d: "Pre-built EIR templates to check fire ratings, load-bearing status, and other required properties",
    feat4t: "Fix-it Guide", feat4d: "AI generates step-by-step Revit instructions that even junior modellers can follow",
    statModels: "Elements Analyzed", statUsers: "Engineers", statTime: "Avg Audit Time",
    login: "Login", signup: "Sign Up", email: "Email", password: "Password",
    loginWith: "Or continue with",
    nav_dash: "Dashboard", nav_viewer: "Viewer", nav_pricing: "Upgrade", nav_settings: "Settings",
    dash_welcome: "Welcome back",
    dash_quick: "Quick Actions",
    dash_upload: "Upload Model", dash_audit: "AI Audits", dash_export: "Export Report",
    dash_active: "Active Projects",
    dash_stats: "Monthly Stats",
    upload_title: "Upload Model File",
    upload_hint: "Drag & drop files here, or click to browse",
    upload_formats: "Formats: IFC · FBX · OBJ · GLB · GLTF",
    upload_note_full: "IFC: 3D viewing + AI data analysis",
    upload_note_view: "FBX / OBJ / GLB: 3D viewing only",
    viewer_ai: "Compliance Report",
    viewer_ai_ready: "Model loaded, running compliance checks...",
    viewer_placeholder: "Have questions? Search compliance items by keyword",
    viewer_fbx_note: "FBX format — view only, AI analysis not available",
    pricing_title: "Choose Your Plan",
    pricing_sub: "Start free, upgrade anytime",
    free: "Free", pro: "Pro", enterprise: "Enterprise",
    free_price: "$0", pro_price: "$19/mo", ent_price: "Contact Us",
    per_month: "/mo",
    current_plan: "Current Plan",
    upgrade: "Upgrade Now",
    contact_sales: "Contact Sales",
    f1: "3 projects", f2: "50MB per file", f3: "Basic AI audit", f4: "Community support",
    p1: "Unlimited projects", p2: "500MB per file", p3: "Deep AI audit", p4: "Export Excel/PDF", p5: "Priority support", p6: "Team collaboration",
    e1: "Private deployment", e2: "Unlimited file size", e3: "Custom AI model", e4: "API access", e5: "Dedicated manager", e6: "SLA guarantee",
    logout: "Log out",
    models_count: "elements",
    status_parsing: "Parsing",
    status_auditing: "Auditing",
    status_done: "Done",
    status_view_only: "View Only",
    lang: "中文",
    col_project: "Project", col_format: "Format", col_elements: "Elements", col_status: "Status", col_date: "Date",
    stat_total_projects: "Projects", stat_elements: "Elements", stat_audits_done: "Audits Done", stat_completeness: "Completeness",
    q1: "Show all naming errors", q2: "Find elements missing Uniclass codes", q3: "Generate EIR compliance report",
    view: "View",
    recommended: "Popular",
  },
};

// ── 设计色板（与 JSX 原版一致）────────────────────────────────
export const S = {
  colors: {
    bg: "#f8f9fb", bg2: "#ffffff", bg3: "#f1f3f9",
    dark: "#0f172a", dark2: "#1e293b", dark3: "#334155",
    accent: "#4f46e5", accent2: "#6366f1", accentLight: "#eef2ff",
    text: "#0f172a", text2: "#475569", text3: "#94a3b8",
    border: "#e2e8f0", border2: "#cbd5e1",
    green: "#10b981", greenBg: "#ecfdf5",
    orange: "#f59e0b", orangeBg: "#fffbeb",
    red: "#ef4444", redBg: "#fef2f2",
    blue: "#3b82f6", blueBg: "#eff6ff",
  },
} as const;

// ── 演示项目数据 ───────────────────────────────────────────────
export const DEMO_PROJECTS: Project[] = [];

// ── AI 关键词回复（Demo 模式） ─────────────────────────────────
export const AI_RESPONSES: Record<string, string> = {};

// ── Speckle 配置（后期替换为真实 stream/model ID）─────────────
// NOTE: 当前使用 Speckle 官方演示流，上线前需替换为自己的 project/model ID
export const SPECKLE_CONFIG = {
  projectId: "3073b96bb1",
  modelId:   "all",
};
