// ================================================================
//  常量定义 — 翻译字典、演示数据、AI 回复、样式色板
// ================================================================

import type { Project, Translations } from "./types";

// ── 双语翻译字典 ──────────────────────────────────────────────
export const T: Record<"zh" | "en", Translations> = {
  zh: {
    brand: "亮阳 BIM·AI",
    tagSub: "智能建筑审计平台",
    hero1: "让 AI 读懂你的",
    hero2: "BIM 模型",
    heroSub: "上传 IFC / FBX，10秒获得专业审计报告。Revit 用户请通过 Speckle Connector 导出 IFC 后上传。",
    cta: "免费开始使用",
    ctaDemo: "查看演示",
    feat1t: "多格式支持", feat1d: "IFC · FBX · OBJ · GLB 一键上传，浏览器即时渲染",
    feat2t: "AI 深度审计", feat2d: "自动检查防火等级、LEED 合规、参数缺失，生成专业报告",
    feat3t: "在线协作",   feat3d: "分享链接即可查看 3D 模型，手机端也能流畅操作",
    feat4t: "数据安全",   feat4d: "企业级加密存储，支持私有化部署，数据完全掌控",
    statModels: "构件已分析", statUsers: "工程师在用", statTime: "平均审计时间",
    login: "登录", signup: "注册", email: "邮箱", password: "密码",
    loginWith: "或使用以下方式登录",
    nav_dash: "工作台", nav_viewer: "模型查看", nav_pricing: "升级 Pro", nav_settings: "设置",
    dash_welcome: "欢迎回来",
    dash_quick: "快速操作",
    dash_upload: "上传新模型", dash_audit: "AI 审计列表", dash_export: "导出报告",
    dash_active: "进行中的项目",
    dash_stats: "本月统计",
    upload_title: "上传模型文件",
    upload_hint: "拖拽文件到此处，或点击选择",
    upload_formats: "支持格式：IFC · FBX · OBJ · GLB · GLTF",
    upload_note_full: "IFC 格式：支持 3D 查看 + AI 数据分析",
    upload_note_view: "FBX / OBJ / GLB 格式：仅支持 3D 查看",
    viewer_ai: "AI 审计助手",
    viewer_ai_ready: "已加载模型数据，可以开始提问",
    viewer_placeholder: "输入问题，例如：模型中有多少面墙？",
    viewer_fbx_note: "当前为 FBX 格式，仅支持 3D 查看，不支持 AI 分析",
    pricing_title: "选择适合你的方案",
    pricing_sub: "从免费开始，随时升级",
    free: "免费版", pro: "专业版", enterprise: "企业版",
    free_price: "¥0", pro_price: "¥99/月", ent_price: "联系我们",
    per_month: "/月",
    current_plan: "当前方案",
    upgrade: "立即升级",
    contact_sales: "联系销售",
    f1: "3 个项目", f2: "50MB 单文件", f3: "基础 AI 审计", f4: "社区支持",
    p1: "无限项目", p2: "500MB 单文件", p3: "深度 AI 审计", p4: "导出 Excel/PDF", p5: "优先支持", p6: "团队协作",
    e1: "私有化部署", e2: "无限文件大小", e3: "定制 AI 模型", e4: "API 接口", e5: "专属客户经理", e6: "SLA 保障",
    logout: "退出登录",
    models_count: "个构件",
    status_parsing: "解析中",
    status_auditing: "审计中",
    status_done: "已完成",
    status_view_only: "仅查看",
    lang: "EN",
    col_project: "项目名称", col_format: "格式", col_elements: "构件数", col_status: "状态", col_date: "日期",
    stat_total_projects: "总项目", stat_elements: "构件总数", stat_audits_done: "审计完成", stat_completeness: "参数完整率",
    q1: "这个模型有多少种构件类型？", q2: "检查缺少参数的构件", q3: "生成 LEED 合规报告",
    view: "查看",
    recommended: "推荐",
  },
  en: {
    brand: "BrightSun BIM·AI",
    tagSub: "Intelligent BIM Audit Platform",
    hero1: "Let AI understand your",
    hero2: "BIM Models",
    heroSub: "Upload IFC / FBX, get professional audit reports in 10 seconds. Revit users: export IFC via Speckle Connector.",
    cta: "Start Free",
    ctaDemo: "View Demo",
    feat1t: "Multi-Format",       feat1d: "IFC · FBX · OBJ · GLB — upload and render instantly in browser",
    feat2t: "AI Deep Audit",      feat2d: "Auto-check fire ratings, LEED compliance, missing parameters",
    feat3t: "Collaborate Online", feat3d: "Share link to view 3D models, works on mobile too",
    feat4t: "Data Security",      feat4d: "Enterprise encryption, private deployment, full data control",
    statModels: "Elements Analyzed", statUsers: "Engineers", statTime: "Avg Audit Time",
    login: "Login", signup: "Sign Up", email: "Email", password: "Password",
    loginWith: "Or continue with",
    nav_dash: "Dashboard", nav_viewer: "Viewer", nav_pricing: "Upgrade", nav_settings: "Settings",
    dash_welcome: "Welcome back",
    dash_quick: "Quick Actions",
    dash_upload: "Upload Model", dash_audit: "AI Audits", dash_export: "Export Report",
    dash_active: "Active Projects",
    dash_stats: "Monthly Stats",
    upload_title: "Upload Model File",
    upload_hint: "Drag & drop files here, or click to browse",
    upload_formats: "Formats: IFC · FBX · OBJ · GLB · GLTF",
    upload_note_full: "IFC: 3D viewing + AI data analysis",
    upload_note_view: "FBX / OBJ / GLB: 3D viewing only",
    viewer_ai: "AI Audit Assistant",
    viewer_ai_ready: "Model data loaded, ready for questions",
    viewer_placeholder: "Ask a question, e.g.: How many walls in this model?",
    viewer_fbx_note: "FBX format — view only, AI analysis not available",
    pricing_title: "Choose Your Plan",
    pricing_sub: "Start free, upgrade anytime",
    free: "Free", pro: "Pro", enterprise: "Enterprise",
    free_price: "$0", pro_price: "$19/mo", ent_price: "Contact Us",
    per_month: "/mo",
    current_plan: "Current Plan",
    upgrade: "Upgrade Now",
    contact_sales: "Contact Sales",
    f1: "3 projects", f2: "50MB per file", f3: "Basic AI audit", f4: "Community support",
    p1: "Unlimited projects", p2: "500MB per file", p3: "Deep AI audit", p4: "Export Excel/PDF", p5: "Priority support", p6: "Team collaboration",
    e1: "Private deployment", e2: "Unlimited file size", e3: "Custom AI model", e4: "API access", e5: "Dedicated manager", e6: "SLA guarantee",
    logout: "Log out",
    models_count: "elements",
    status_parsing: "Parsing",
    status_auditing: "Auditing",
    status_done: "Done",
    status_view_only: "View Only",
    lang: "中文",
    col_project: "Project", col_format: "Format", col_elements: "Elements", col_status: "Status", col_date: "Date",
    stat_total_projects: "Projects", stat_elements: "Elements", stat_audits_done: "Audits Done", stat_completeness: "Completeness",
    q1: "What element types are in this model?", q2: "Check for missing parameters", q3: "Generate LEED compliance report",
    view: "View",
    recommended: "Popular",
  },
};

// ── 设计色板（与 JSX 原版一致）────────────────────────────────
export const S = {
  colors: {
    bg: "#f8f9fb", bg2: "#ffffff", bg3: "#f1f3f9",
    dark: "#0f172a", dark2: "#1e293b", dark3: "#334155",
    accent: "#4f46e5", accent2: "#6366f1", accentLight: "#eef2ff",
    text: "#0f172a", text2: "#475569", text3: "#94a3b8",
    border: "#e2e8f0", border2: "#cbd5e1",
    green: "#10b981", greenBg: "#ecfdf5",
    orange: "#f59e0b", orangeBg: "#fffbeb",
    red: "#ef4444", redBg: "#fef2f2",
    blue: "#3b82f6", blueBg: "#eff6ff",
  },
} as const;

// ── 演示项目数据 ───────────────────────────────────────────────
export const DEMO_PROJECTS: Project[] = [
  { id: 1, name: "高庄子托老所_含机电", format: "IFC", elements: 6549, status: "done",      progress: 100, date: "2026-04-05", speckleStreamId: "c4c835cd7e", speckleModelId: "99a7e3f71c" },
  { id: 2, name: "朝阳区办公楼_结构",   format: "RVT", elements: 3280, status: "auditing",  progress: 72,  date: "2026-04-06" },
  { id: 3, name: "展厅外观概念模型",     format: "FBX", elements: 0,    status: "view_only", progress: 100, date: "2026-04-04" },
  { id: 4, name: "海淀科技园_暖通",     format: "IFC", elements: 0,    status: "parsing",   progress: 35,  date: "2026-04-06" },
];

// ── AI 关键词回复（Demo 模式） ─────────────────────────────────
export const AI_RESPONSES: Record<string, string> = {
  "构件": "**高庄子托老所模型统计：**\n\n共 6,549 个构件，主要类型：\n• 墙体 (Wall) — 823 个\n• 管道 (Pipe) — 1,247 个\n• 风管 (Duct) — 456 个\n• 门 (Door) — 312 个\n• 窗 (Window) — 198 个\n• 桥架 (Cable Tray) — 267 个\n• 其他 — 3,246 个",
  "墙":   "模型中共有 **823 面墙**，其中：\n• 内墙 — 612 面\n• 外墙 — 211 面\n• 防火墙 — 47 面\n\n⚠️ 发现 **23 面墙** 缺少防火等级参数，建议立即补全。",
  "管道": "**管道系统：** 共 1,247 根\n• 给水管 — 389 根\n• 排水管 — 298 根\n• 消防管 — 267 根\n• 暖通管 — 293 根\n\n✅ 消防管道覆盖率达标\n⚠️ 12 根给水管缺少材质参数",
  "LEED": "**LEED 合规检查结果：**\n\n✅ WE 节水: 卫生器具参数完整\n✅ EA 能源: 保温层厚度达标\n⚠️ EQ 室内环境: 3 处新风口未标注风量\n❌ MR 材料: 15% 构件缺少材料信息\n\n总分预估: **62/100** — 需要补全材料数据",
  "缺少": "**参数完整性审计：**\n\n❌ 防火等级缺失: 23 面墙 + 8 扇门\n❌ 材质缺失: 12 根管道 + 45 个配件\n⚠️ 标高偏移缺失: 89 个机电构件\n⚠️ 系统分类缺失: 34 个风管\n\n完整性: **87.3%** — 建议优先处理防火等级",
};

// ── Speckle 配置（后期替换为真实 stream/model ID）─────────────
// NOTE: 当前使用 Speckle 官方演示流，上线前需替换为自己的 project/model ID
export const SPECKLE_CONFIG = {
  projectId: "3073b96bb1",
  modelId:   "all",
};
